name: DevSecOps Workflow for MyVodafoneApp
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build Job is going on"
          sleep 20

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo "test Job is going on"
          sleep 20

  oast-retire:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v2

      - name: Install Retire.JS
        run: npm install -g retire

      - name: Install Node Modules
        run: npm install

      - name: run Retire.JS Scan
        run: | 
          retire --outputformat json --outputpath retire_output.json --exitwith 0
          echo $?

  deployment:
    runs-on: ubuntu-latest
    needs: oast-retire
    steps:
      - run: |
          echo "deployment Job is going on"
          sleep 20



